package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Host;
import ba.unsa.etf.rpr.exceptions.Exceptionss;

public class HostManager {


    public Host add(Host host) throws Exceptionss {
        if (host.getId() != 0){
            throw new Exceptionss("Can't add category with ID. ID is autogenerated");
        }

        try{
            return DaoFactory.HostDao().add(host);
        }catch (Exceptionss e){
            if (e.getMessage().contains("UQ_NAME")){
                throw new Exceptionss("Category with same name exists");
            }
            throw e;
        }
    }

    public Host update(Host host) throws Exceptionss {

        try{
            return DaoFactory.HostDao().update(host);
        }catch (Exceptionss e){
            if (e.getMessage().contains("UQ_NAME")){
                throw new Exceptionss("Category with same name exists");
            }
            throw e;
        }
    }


}
