package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Host;
import ba.unsa.etf.rpr.domain.Property;
import ba.unsa.etf.rpr.exceptions.Exceptionss;

public class PropertyManager {
    public Property add(Property  property) throws Exceptionss {
        if ( property.getId() != 0){
            throw new Exceptionss("Can't add category with ID. ID is autogenerated");
        }

        try{
            return DaoFactory.propertyDao().add(property);
        }catch (Exceptionss e){
            if (e.getMessage().contains("UQ_NAME")){
                throw new Exceptionss("Category with same name exists");
            }
            throw e;
        }
    }

    public Property  update(Property  property) throws Exceptionss {

        try{
            return DaoFactory.propertyDao().update(property);
        }catch (Exceptionss e){
            if (e.getMessage().contains("UQ_NAME")){
                throw new Exceptionss("Category with same name exists");
            }
            throw e;
        }
    }

    public void delete(Property property) throws Exceptionss {

        try{
             DaoFactory.propertyDao().delete(property.getId());
        }catch (Exceptionss e){
            if (e.getMessage().contains("UQ_NAME")){
                throw new Exceptionss("Category with same name exists");
            }
            throw e;
        }
    }

}
